# Generated by Django 4.1 on 2022-08-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-10-06'),
            preserve_default=False,
        ),
    ]
